### ISSUE TITLE
webhookリクエストのContent-Typeが application/x-www-form-urlencoded になっている

### ISSUE THREAD

**Issue by hideyuki** [Coiney-SDK/CoineyKit-Payge#1]
## :pushpin: APIバージョン
- v1 
- X-CoineyPayge-Version: 2016-08-31
## :pencil2: 再現方法

https://api.coiney.io/api/v1/payments APIで生成された決済URLで実際に決済を行った直後の
決済完了webhookリクエスト全般。
## :bug: 実際の結果

webhookリクエストのContent-Typeが `application/x-www-form-urlencoded` になっている。
## :sunny: 想定される結果

[ドキュメント](https://github.com/Coiney-SDK/CoineyKit-Payge/blob/master/user-guides/webhook.md) では `application/json` の指定があるので、ドキュメントを変更するかリクエスト形式を変更されるのが良いかと思います。

**Comment by isamisushi** [comment]
@hideyuki 

ご報告ありがとうございます。迅速に対応させていただきます。

**Comment by isamisushi** [comment]
@hideyuki 

修正版をリリースしました。ご迷惑をおかけしました、これからもよろしくお願いいたします。
